language: python
python:
- '2.7'
branches:
  except:
  - master
  - ansible
script: 'true'
deploy:
  provider: pypi
  user: f3flight
  password:
    secure: xGGn2tkUzbNSDj4woc8Lf5zO1H0CRdDTusj31BANrgGVdc19Zf3KC1sc6VbMxJeXDRtYFgwMrxufx4nP/3nAwxVuXTAjwPQwpw62VQnUiAGK0xRKySC4vJqsfcZShtVpgmdcZlQXclNtjmJI4bWrcUWzStEjMTpWd6EGmSReiDLPoc/6QHsiu8naNQhpgf0T7nonHThHEK/ulRbD/QKcY/o3Q6+i/X865ysHgblXARDe/MLjwaMbURkHgFt4AZGlcVZ0AWJQNmgs5wU8BvutMlLeqrIo9+niv9jnx0Bj6EeMGLKu9sDwDgI5clox1RWYhW7Ts3jOtCfZqpPmHTS2aV3YVTUOWIWYsDY50Up7ZWDEzUqfDFcwzIi5pXxayecJwoNAXO0j9YTifXPynKSU/gbV5TMk//6Dq9QTGiB4nw28z/6uX1bafrelISjnUPGteZTNH1WdEp8yAJhOIwqxoKgKe/Yhwltp7Wxga7+C13PaaAhk3zU9nMAl1LsQaT0Ag+S7ECjsOr7a8gJpENHH14nsnXnUr+3iid0upLcBSgF78n6jkSPtmljaxcJQ7W9E2+a92Ux2zeA4/lBUrT6z5zIKHwS6bs/boWYhG8N0v5TMhX57wUlk5BIBqaG3zgOv8vF4RFtxtag1uNNnxb81jNrUmv+wpKqxG6gbCKtAdYQ=
  on:
    tags: true
